
import React, { useState, useEffect } from 'react';
import { CompanyConfig, Product } from '../types';
import { supabase } from '../lib/supabase';
import { LOGO_URL } from '../constants';
import { syncProductsFromOdoo } from '../services/odooService';

interface AdminPanelProps {
  onClose: () => void;
  config: CompanyConfig | null;
  products: Product[];
  onRefresh: () => void;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({ onClose, config, products, onRefresh }) => {
  const [activeTab, setActiveTab] = useState<'config' | 'banners' | 'odoo' | 'orders' | 'help'>('config');
  const [formData, setFormData] = useState<any>(config || { banners: [] });
  const [orders, setOrders] = useState<any[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [syncStatus, setSyncStatus] = useState<{msg: string, type: 'success' | 'error' | 'none'}>({msg: '', type: 'none'});

  useEffect(() => {
    if (config) setFormData(config);
  }, [config]);

  useEffect(() => {
    if (activeTab === 'orders') {
      fetchOrders();
    }
  }, [activeTab]);

  const fetchOrders = async () => {
    const { data } = await supabase
      .from('orders')
      .select('*, order_items(*)')
      .order('created_at', { ascending: false });
    setOrders(data || []);
  };

  const handleSaveConfig = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSaving(true);
    try {
      const { error } = await supabase
        .from('settings')
        .update({
          company_name: formData.company_name,
          logo_url: formData.logo_url,
          whatsapp_number: formData.whatsapp_number,
          facebook_url: formData.facebook_url,
          instagram_url: formData.instagram_url,
          odoo_host: formData.odoo_host,
          odoo_db: formData.odoo_db,
          odoo_username: formData.odoo_username,
          odoo_api_key: formData.odoo_api_key,
          banners: formData.banners
        })
        .eq('id', 1);

      if (error) throw error;
      setSyncStatus({msg: "Configuración guardada", type: 'success'});
      onRefresh();
    } catch (error: any) {
      setSyncStatus({msg: "Error al guardar. Revise la consola.", type: 'error'});
    } finally {
      setIsSaving(false);
      setTimeout(() => setSyncStatus({msg: '', type: 'none'}), 4000);
    }
  };

  const handleSync = async () => {
    if (!formData.odoo_host || !formData.odoo_api_key) {
      alert("Por favor complete los datos de Odoo antes de sincronizar.");
      return;
    }
    setIsSyncing(true);
    setSyncStatus({msg: 'Sincronizando +1,000 productos...', type: 'none'});
    try {
      const result = await syncProductsFromOdoo(formData);
      setSyncStatus({msg: `¡Éxito! ${result.count} productos actualizados.`, type: 'success'});
      onRefresh();
    } catch (error: any) {
      setSyncStatus({msg: error.message, type: 'error'});
    } finally {
      setIsSyncing(false);
    }
  };

  const sqlCode = `-- COPIA Y PEGA ESTO EN TU SQL EDITOR DE SUPABASE
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  odoo_id INTEGER UNIQUE,
  name TEXT NOT NULL,
  price DECIMAL(10,2) DEFAULT 0,
  qty_available INTEGER DEFAULT 0,
  image_url TEXT,
  category_name TEXT,
  default_code TEXT,
  description_sale TEXT,
  uom_name TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  company_name TEXT,
  logo_url TEXT,
  whatsapp_number TEXT,
  odoo_host TEXT,
  odoo_db TEXT,
  odoo_username TEXT,
  odoo_api_key TEXT,
  banners JSONB DEFAULT '[]'
);

INSERT INTO settings (id, company_name) VALUES (1, 'GIOFARMA') ON CONFLICT DO NOTHING;`;

  return (
    <div className="fixed inset-0 z-[100] bg-white flex flex-col">
      <div className="bg-[#1a2b49] text-white p-6 flex justify-between items-center shadow-lg">
        <div className="flex items-center gap-4">
          <img src={formData.logo_url || LOGO_URL} className="h-10 object-contain brightness-0 invert" alt="Logo" />
          <h2 className="text-xl font-black uppercase tracking-tighter italic">Panel GIOFARMA</h2>
        </div>
        <button onClick={onClose} className="bg-white/10 hover:bg-white/20 px-8 py-3 rounded-2xl font-black text-xs uppercase tracking-widest transition-all">
          Volver a la Tienda
        </button>
      </div>

      <div className="flex flex-grow overflow-hidden">
        <aside className="w-72 bg-gray-50 border-r border-gray-100 p-8 space-y-3">
          <button onClick={() => setActiveTab('config')} className={`w-full text-left px-6 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest flex items-center gap-4 transition-all ${activeTab === 'config' ? 'bg-[#e1127a] text-white shadow-xl scale-105' : 'text-gray-400 hover:bg-gray-100'}`}>
            <i className="fas fa-cog"></i> Ajustes
          </button>
          <button onClick={() => setActiveTab('odoo')} className={`w-full text-left px-6 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest flex items-center gap-4 transition-all ${activeTab === 'odoo' ? 'bg-blue-600 text-white shadow-xl scale-105' : 'text-gray-400 hover:bg-gray-100'}`}>
            <i className="fas fa-sync-alt"></i> Odoo Sync
          </button>
          <button onClick={() => setActiveTab('orders')} className={`w-full text-left px-6 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest flex items-center gap-4 transition-all ${activeTab === 'orders' ? 'bg-[#a5cf4c] text-white shadow-xl scale-105' : 'text-gray-400 hover:bg-gray-100'}`}>
            <i className="fas fa-shopping-cart"></i> Pedidos
          </button>
          <div className="pt-8 mt-8 border-t border-gray-200">
            <button onClick={() => setActiveTab('help')} className={`w-full text-left px-6 py-4 rounded-2xl font-black text-[11px] uppercase tracking-widest flex items-center gap-4 transition-all ${activeTab === 'help' ? 'bg-yellow-500 text-white shadow-xl' : 'text-yellow-600 bg-yellow-50 hover:bg-yellow-100'}`}>
              <i className="fas fa-terminal"></i> Configurar SQL
            </button>
          </div>
        </aside>

        <main className="flex-grow overflow-y-auto p-12 bg-white relative">
          {syncStatus.msg && (
            <div className={`fixed top-24 right-12 px-8 py-4 rounded-2xl font-black text-xs uppercase tracking-widest shadow-2xl z-50 animate-in slide-in-from-top ${
              syncStatus.type === 'success' ? 'bg-green-500 text-white' : syncStatus.type === 'error' ? 'bg-red-500 text-white' : 'bg-blue-500 text-white'
            }`}>
              {syncStatus.msg}
            </div>
          )}

          {activeTab === 'config' && (
            <form onSubmit={handleSaveConfig} className="max-w-4xl space-y-10 animate-in fade-in duration-500">
              <h3 className="text-2xl font-black text-[#1a2b49] uppercase italic tracking-tighter">Configuración General</h3>
              <div className="grid grid-cols-2 gap-8 bg-gray-50 p-10 rounded-[40px]">
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest">Nombre de la Empresa</label>
                  <input type="text" value={formData.company_name} onChange={e => setFormData({...formData, company_name: e.target.value})} className="w-full p-4 rounded-2xl font-bold border-2 border-transparent focus:border-[#e1127a] outline-none" />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest">WhatsApp (51XXXXXXXXX)</label>
                  <input type="text" value={formData.whatsapp_number} onChange={e => setFormData({...formData, whatsapp_number: e.target.value})} className="w-full p-4 rounded-2xl font-bold border-2 border-transparent focus:border-[#e1127a] outline-none" />
                </div>
                <div className="col-span-2 space-y-2">
                  <label className="text-[10px] font-black text-gray-400 uppercase tracking-widest">URL del Logo</label>
                  <input type="text" value={formData.logo_url} onChange={e => setFormData({...formData, logo_url: e.target.value})} className="w-full p-4 rounded-2xl font-bold border-2 border-transparent focus:border-[#e1127a] outline-none" />
                </div>
              </div>
              <button type="submit" disabled={isSaving} className="bg-[#1a2b49] text-white px-12 py-5 rounded-3xl font-black uppercase text-xs tracking-widest shadow-xl hover:bg-[#e1127a] transition-all disabled:opacity-50">
                {isSaving ? 'Guardando...' : 'Actualizar Información'}
              </button>
            </form>
          )}

          {activeTab === 'odoo' && (
            <div className="max-w-4xl space-y-10 animate-in fade-in duration-500">
              <h3 className="text-2xl font-black text-[#1a2b49] uppercase italic tracking-tighter">Sincronización con Odoo</h3>
              <div className="bg-blue-50/50 p-10 rounded-[40px] border-2 border-blue-100 space-y-8">
                <div className="grid grid-cols-2 gap-8">
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-blue-400 uppercase tracking-widest">Instancia de Odoo (Host)</label>
                    <input type="text" value={formData.odoo_host} onChange={e => setFormData({...formData, odoo_host: e.target.value})} className="w-full p-4 rounded-2xl font-bold bg-white border-2 border-transparent focus:border-blue-500 outline-none" placeholder="midominio.odoo.com" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] font-black text-blue-400 uppercase tracking-widest">API Key / Contraseña</label>
                    <input type="password" value={formData.odoo_api_key} onChange={e => setFormData({...formData, odoo_api_key: e.target.value})} className="w-full p-4 rounded-2xl font-bold bg-white border-2 border-transparent focus:border-blue-500 outline-none" />
                  </div>
                </div>
                <div className="flex items-center gap-6">
                  <button onClick={handleSync} disabled={isSyncing} className="bg-blue-600 text-white px-10 py-5 rounded-2xl font-black uppercase text-[11px] tracking-widest flex items-center gap-4 shadow-xl hover:bg-blue-700 disabled:opacity-50 transition-all">
                    {isSyncing ? <i className="fas fa-spinner animate-spin"></i> : <i className="fas fa-cloud-download-alt"></i>}
                    Sincronizar +1000 Productos
                  </button>
                  <p className="text-xs font-bold text-blue-400 max-w-sm">Esta acción actualizará precios, stock e imágenes directamente desde tu inventario central.</p>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'help' && (
            <div className="max-w-4xl space-y-8 animate-in fade-in duration-500">
              <h3 className="text-2xl font-black text-yellow-600 uppercase italic tracking-tighter">Guía de Conexión</h3>
              <div className="bg-yellow-50 p-10 rounded-[40px] border-2 border-yellow-100 space-y-6">
                <p className="font-bold text-yellow-800">1. Ejecuta este código en el SQL Editor de Supabase:</p>
                <div className="relative">
                  <pre className="bg-white p-6 rounded-2xl text-[11px] font-mono text-gray-600 overflow-x-auto border border-yellow-200">
                    {sqlCode}
                  </pre>
                  <button onClick={() => navigator.clipboard.writeText(sqlCode)} className="absolute top-4 right-4 bg-yellow-500 text-white p-2 rounded-lg text-xs font-black">COPIAR</button>
                </div>
                <div className="pt-6 border-t border-yellow-100">
                  <p className="font-bold text-yellow-800 mb-4">2. Crea la Edge Function:</p>
                  <p className="text-sm text-yellow-700 leading-relaxed">
                    Debes desplegar una función llamada <code>odoo-sync-massive</code> en tu proyecto de Supabase. Esta función es la que realiza la conexión XML-RPC con Odoo de forma segura. Sin esta función, el botón de sincronizar no tendrá efecto.
                  </p>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'orders' && (
            <div className="animate-in fade-in duration-500">
              <h3 className="text-2xl font-black text-[#1a2b49] uppercase italic tracking-tighter mb-8">Pedidos Recientes</h3>
              <div className="grid grid-cols-1 gap-6">
                {orders.length === 0 ? (
                  <div className="text-center py-20 bg-gray-50 rounded-[40px] border-2 border-dashed border-gray-200">
                    <i className="fas fa-box-open text-4xl text-gray-200 mb-4"></i>
                    <p className="font-black text-gray-400 uppercase text-xs">No hay pedidos registrados aún</p>
                  </div>
                ) : (
                  orders.map(order => (
                    <div key={order.id} className="bg-white border-2 border-gray-50 p-8 rounded-[32px] hover:border-pink-100 transition-all flex justify-between items-center group">
                      <div>
                        <div className="flex items-center gap-4 mb-2">
                          <span className="text-lg font-black text-[#1a2b49]">#{order.id.split('-')[0].toUpperCase()}</span>
                          <span className="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-[9px] font-black uppercase">{order.status}</span>
                        </div>
                        <p className="text-xs font-bold text-gray-400">{order.customer_name} • {order.customer_phone}</p>
                      </div>
                      <div className="text-right">
                        <span className="block text-[10px] font-black text-gray-400 uppercase mb-1">Total</span>
                        <span className="text-2xl font-black text-[#e1127a]">S/ {order.total_amount.toFixed(2)}</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
};
